### ISSUE TITLE
Rename Theme folder and name

### ISSUE THREAD

**Issue by kellsbells** [kellsbells/dooverdogs#3]
Theme folder 'dod-round-two' should be renamed to 'dod' and the name should be 'Do Over Dogs'

**Comment by logichub** [comment]
Another folder with a name _dod_ is already present. It is not possible to keep two folders with a same name. You can do either of the following:

1. Rename the existing _dod_ folder to _dod-old_ and then rename the _dod-round-two_ folder as _dod_.
2. Delete the existing _dod_ folder and then rename the _dod-round-two_ folder as _dod_.
3. Keep existing _dod_ folder as it is and rename the _dod-round-two_ folder as _dod-2_.
